#!/usr/bin/perl

use strict;
use warnings  qw(FATAL utf8);

my %substitutes = (
    "Subway Helsinki Sornai"        => 'Subway',
    'Asunto Oy Vantaan Kuurankukka' => 'Kuurankukka',
    'SLM FINLAND OY'                => 'Pizza-online',
    'GOFORE OY'                     => 'Gofore'
);

open(my $inFile, '<:encoding(UTF-8)', './SP')
    or die "Could not open file 'SP' $!";

print "Date,Payee,Category,Memo,Outflow,Inflow\n";
while (<$inFile>) {
    chomp;
    (my $date, my $payee, my $amount, my $total, my $status, my $check) = split /;/;

    next if ($date eq '"Pvm"');
    next if ($check eq '"Ei"');

    $date =~ s/"//g;
    $date =~ s/\./\//g;

    $payee =~ s/"//g;
    $payee =~ s/\s+\)+$//;

    $amount =~ s/"//g;
    $amount =~ s/ //g;
    $amount =~ s/,/./;
    my $inflow = '';
    my $outflow = '';
    if ($amount =~ m/^-/) {
        $outflow = $amount;
        $outflow =~ s/^-//;
    } else {
        $inflow = $amount;
    }

    $payee = $substitutes{$payee} if defined $substitutes{$payee};

    print "$date,$payee,,,$outflow,$inflow\n";
}
