#!/usr/bin/perl

use strict;
# use warnings;
use warnings  qw(FATAL utf8);

open(my $inFile, '<:encoding(UTF-8)', './SP')
    or die "Could not open file 'SP' $!";

print "Date,Payee,Category,Memo,Outflow,Inflow\n";
while (<$inFile>) {
    chomp;
    (my $date, my $payee, my $amount, my $total, my $status, my $check) = split /;/;
    next if ($date eq '"Pvm"');

    next if $check eq '"Ei"';
    $date =~ s/"//g;
    $date =~ s/\./\//g;
    $payee =~ s/"//g;
    $payee =~ s/\s+\)+$//;
    $amount =~ s/"//g;
    $amount =~ s/ //g;
    $amount =~ s/,/./;
    my $inflow = '';
    my $outflow = '';
    if ($amount =~ m/^-/) {
        $outflow = $amount;
        $outflow =~ s/^-//;
    } else {
        $inflow = $amount;
    }

    print "$date,$payee,,,$outflow,$inflow\n";

}
