#!/usr/bin/perl

use warnings;
use strict;

my @people;

# my_people on lista kiinnostavista nimistä. Yksi nimi rivillä, tyyliin
# Etunimi Sukunimi
# Tokanimi Jne
#
# Macilla voi kivasti kopioida listan leikepöydälle ja ajaa ´pbpaste | rapsa´.

open(my $inFile, '<:encoding(UTF-8)', "./my_people")
    or die "Could not open file './my_people' $!";

while (<$inFile>) {
    chomp;
    push @people, $_;
}

while (<>) {
    chomp;
    next unless /^\>/;
    my @parts = split / /;
    my $lastname = $parts[2];
    $lastname =~ s/,.*$//;
    my $firstname = $parts[3];
    my $name = $firstname . " " . $lastname;
    my $records = $parts[4];
    my $billable = $parts[5];

    next unless (grep( /^$name$/, @people ));
    print "$name $records $billable\n";
}
